{
 "title": "Monitoring \"Four Golden Signals\"",
 "time": { "from": "2023-03-12T11:42:00.000Z", "to": "2023-03-12T11:58:00.000Z" },
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency loadgenerator to frontend ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{reporter='source',source_app='loadgenerator',destination_app='frontend'}[30s])) by (source_app, destination_app) / sum(rate(istio_request_duration_milliseconds_count{reporter='source', source_app='loadgenerator',destination_app='frontend'}[30s])) by (source_app, destination_app)"
    }
   ]
  },
  {
   "title": "Latency All Microservices",
   "type": "timeseries",
   "gridPos": { "h": 26, "w": 14, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{reporter='source',source_app!='loadgenerator'}[30s])) by (source_app, destination_app) / sum(rate(istio_request_duration_milliseconds_count{reporter='source', destination_app!='unknown',source_app!='loadgenerator'}[30s])) by (source_app, destination_app)"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(istio_requests_total{reporter='source',response_code='200',source_app='loadgenerator',destination_app='frontend'}[30s])"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "1 Minute 99th Percentile Response Time ",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(istio_request_duration_milliseconds_bucket{reporter='source',response_code=\"200\", response_flags=\"-\", source_app=\"loadgenerator\",destination_app=\"frontend\"}[1m]) )"
    }
   ]
  },
  {
   "title": "Node Cpu %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode='idle'}[2m])) * 100)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", response_code=~\"5.*\"}[2m])) by (source_app, destination_app)\n"
    }
   ]
  }
 ]
}