{
 "title": "Monitoring \"Four Golden Signals\"",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{namespace!=\"\",pod!=\"\",reporter=\"destination\"}[1m]) > 0) by (pod) / sum(rate(istio_request_duration_milliseconds_count{namespace!=\"\",pod!=\"\",reporter=\"destination\"}[1m]) > 0) by (pod)"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Latency All Microservices",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{reporter='source',source_app!='loadgenerator'}[30s])) by (source_app, destination_app) / sum(rate(istio_request_duration_milliseconds_count{reporter='source', destination_app!='unknown',source_app!='loadgenerator'}[30s])) by (source_app, destination_app)"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "rate(istio_requests_total{reporter='source',response_code='200',source_app='loadgenerator',destination_app='frontend'}[30s])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 29 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace='default',deployment!='kube-state-metrics'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,rate(istio_request_duration_milliseconds_bucket{reporter='source',response_code=\"200\", response_flags=\"-\", source_app=\"loadgenerator\",destination_app=\"frontend\"}[30s]))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90,rate(istio_request_duration_milliseconds_bucket{reporter='source',response_code=\"200\", response_flags=\"-\", source_app=\"loadgenerator\",destination_app=\"frontend\"}[30s]))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99,rate(istio_request_duration_milliseconds_bucket{reporter='source',response_code=\"200\", response_flags=\"-\", source_app=\"loadgenerator\",destination_app=\"frontend\"}[30s]))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Latency loadgenerator to frontend ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{reporter='source',source_app='loadgenerator',destination_app='frontend'}[30s])) by (source_app, destination_app) / sum(rate(istio_request_duration_milliseconds_count{reporter='source', source_app='loadgenerator',destination_app='frontend'}[30s])) by (source_app, destination_app)"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "1 Minute 99th Percentile Response Time ",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(istio_request_duration_milliseconds_bucket{reporter='source',response_code=\"200\", response_flags=\"-\", source_app=\"loadgenerator\",destination_app=\"frontend\"}[1m]) )"
    }
   ]
  },
  {
   "title": "Node Cpu %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 5, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode='idle'}[2m])) * 100)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 13, "y": 45 },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", response_code=~\"5.*\"}[2m])) by (source_app, destination_app)\n"
    }
   ]
  }
 ]
}