{
 "title": "Monitoring SLI Istio Microservices",
 "description": " The dashboard is designed to display the Service Level Indicators (SLIs) of the microservices, which help to measure the quality of the service provided by the microservices.",
 "time": { "from": "2023-03-12T11:42:00.000Z", "to": "2023-03-12T11:58:00.000Z" },
 "templating": {
  "list": [
   { "name": "destination_workload", "query": "frontend" },
   { "name": "source", "query": "loadgenerator" }
  ]
 },
 "panels": [
  {
   "title": "Response Time Distribution",
   "type": "histogram",
   "gridPos": { "h": 15, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le))"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le))"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace,destination_service, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload,destination_service, destination_workload_namespace, le))"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le))"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le))"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le))"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le))"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$destination_workload\"}[1m])) by (destination_workload, destination_workload_namespace, le))"
    }
   ]
  },
  {
   "title": "99th Percentile Response Time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(istio_request_duration_milliseconds_bucket{reporter='source',response_code=\"200\", response_flags=\"-\", source_app=~\"$source\",destination_app=~\"$destination_workload\"}[20m]) )\n"
    }
   ]
  },
  {
   "title": "90th Percentile Response Time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90,rate(istio_request_duration_milliseconds_bucket{reporter='source',response_code=\"200\", response_flags=\"-\", source_app=~\"$source\",destination_app=~\"$destination_workload\"}[20m]) )\n"
    }
   ]
  },
  {
   "title": "50th Percentile Response Time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,rate(istio_request_duration_milliseconds_bucket{reporter='source',response_code=\"200\", response_flags=\"-\", source_app=~\"$source\",destination_app=~\"$destination_workload\"}[20m]) )\n"
    }
   ]
  },
  {
   "title": "Availability ",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"source\", response_code!~\"5.*\"}[20m]))\n\n/\n\nsum(rate(istio_requests_total{reporter=\"source\"}[20m]))\n"
    }
   ]
  },
  {
   "title": "Response Time Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{reporter='source',source_app='loadgenerator',destination_app='frontend'}[30s])) by (source_app, destination_app) / sum(rate(istio_request_duration_milliseconds_count{reporter='source', source_app='loadgenerator',destination_app='frontend'}[30s])) by (source_app, destination_app)"
    }
   ]
  }
 ]
}