apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recommendationservice
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 3
  behavior:
      scaleDown:
        stabilizationWindowSeconds: 60
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_requests_restime_2m
      target:
        type: AverageValue
        averageValue: 40000m # 400ms

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recommendationservice

status:
  currentMetrics:
  - resource:
      current:
        averageUtilization: 2
        averageValue: 5m
      name: cpu
    type: Resource
  currentReplicas: 1
  desiredReplicas: 1
