apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 5
  behavior:       
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 240ss 
  metrics:

  - type: Pods
    pods:
      metric:
        name: restime_99_percentile
      target:
        type: AverageValue
        averageValue: 450000m # 850ms

  - type: Pods
    pods:
      metric:
        name: restime_90_percentile
      target:
        type: AverageValue
        averageValue: 200000m # 450ms

  - type: Pods
    pods:
      metric:
        name: restime_50_percentile
      target:
        type: AverageValue
        averageValue: 80000m # 80ms
  
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
status:
  currentMetrics:
  - resource:
      current:
        averageUtilization: 2
        averageValue: 5m
      name: cpu
    type: Resource
  currentReplicas: 1
  desiredReplicas: 1
