apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
  - type: Pods
    pods:
      metric:
        name: restime_99_percentile
      target:
        type: AverageValue
        averageValue: 90000m # 900ms
  - type: Pods
    pods:
      metric:
        name: restime_90_percentile
      target:
        type: AverageValue
        averageValue: 45000m # 450ms
  


  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
status:
  currentMetrics:
  - resource:
      current:
        averageUtilization: 2
        averageValue: 5m
      name: cpu
    type: Resource
  currentReplicas: 1
  desiredReplicas: 1
