apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: checkoutservice
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 2
  # behavior:
  #     scaleDown:
  #       stabilizationWindowSeconds: 120
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 15

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: checkoutservice

status:
  currentMetrics:
  - resource:
      current:
        averageUtilization: 2
        averageValue: 5m
      name: cpu
    type: Resource
  currentReplicas: 1
  desiredReplicas: 1
